#!/bin/sh
# IBM(c) 2014 Apache 2.0
# chkconfig: 345 85 60
# description: Confluent hardware manager

### BEGIN INIT INFO
# Provides: confluent
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
### END INIT INFO
if [ -f /etc/init.d/functions ]; then
    . /etc/init.d/functions
    LOG_SUCCESS=success
elif [ -f /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions
    LOG_SUCCESS=log_success_msg
else
    echo "Unknown platform"
    exit 1
fi

confluent=/opt/confluent/bin/confluent
confetty=/opt/confluent/bin/confetty

stop() {
	echo -n 'Stopping Confluent: '
	if [ -S /var/run/confluent/api.sock ]; then
		$confetty shutdown /
	fi
	$LOG_SUCCESS
	echo
	return
}

start() {
	echo -n 'Starting Confluent: '
	$confluent
	$LOG_SUCCESS
	echo
	return
}

case $1 in
	restart)
		stop
		start
		;;
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status -p /var/run/confluent/pid $confluent
		;;
esac

