#!/bin/sh
dracut_install curl openssl tar ipmitool cpio gzip lsmod ethtool
dracut_install modprobe touch echo cut wc bash netstat uniq grep ip hostname
dracut_install awk egrep dirname bc expr sort
dracut_install ssh sshd vi reboot lspci parted tmux mkfs mkfs.ext4 mkfs.xfs xfs_db mkswap
dracut_install efibootmgr
dracut_install du df ssh-keygen scp clear dhclient lldpd lldpcli tee
dracut_install /lib64/libnss_dns-2.28.so /lib64/libnss_dns.so.2
dracut_install ldd uptime /usr/lib64/libnl-3.so.200
dracut_install poweroff date /etc/nsswitch.conf /etc/services /etc/protocols
dracut_install  /usr/share/terminfo/x/xterm /usr/share/terminfo/l/linux /usr/share/terminfo/v/vt100 /usr/share/terminfo/x/xterm-color /usr/share/terminfo/s/screen /usr/share/terminfo/x/xterm-256color /usr/share/terminfo/p/putty-256color /usr/share/terminfo/p/putty /usr/share/terminfo/d/dumb
dracut_install chmod ifconfig whoami route head tail basename /etc/redhat-release ping tr lsusb /usr/share/hwdata/usb.ids
dracut_install dmidecode /usr/lib64/libstdc++.so.6
dracut_install ps free find
inst /bin/bash /bin/sh
inst_hook cmdline 10 $moddir/cmdline.sh
dracut_install killall chown chroot dd expr kill parted rsync shutdown sort blockdev findfs insmod lvm pivot_root
dracut_install /etc/udev/hwdb.bin
dracut_install /usr/share/hwdata/pci.ids
#dracut_install mstflint This would have mlx update support, but it incurs gigantic dependencies, libicudata
