#!/bin/bash
VERSION=`git describe|cut -d- -f 1`
NUMCOMMITS=`git describe|cut -d- -f 2`
if [ "$NUMCOMMITS" != "$VERSION"  ]; then
    VERSION=$VERSION.dev$NUMCOMMITS.g`git describe|cut -d- -f 3`
fi
sed -e "s/#VERSION#/$VERSION/" confluent_imgutil.spec.tmpl > confluent_imgutil.spec
cp ../LICENSE .
cd ..
tar Jcvf confluent_imgutil.tar.xz imgutil
mv confluent_imgutil.tar.xz ~/rpmbuild/SOURCES/
cd -
rpmbuild -ba confluent_imgutil.spec
