#!/bin/bash
cd $(dirname $0)
VERSION=`../mkversion --tilde` || exit 1
sed -e "s/#VERSION#/$VERSION/" confluent_imgutil.spec.tmpl > confluent_imgutil.spec
cp ../LICENSE .
cd ..
tar Jcvf confluent_imgutil.tar.xz imgutil
mv confluent_imgutil.tar.xz ~/rpmbuild/SOURCES/
cd -
rpmbuild -ba confluent_imgutil.spec
